version: 0.2  
phases:  
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket code-pipeline-p1 --output-template-file search.yaml
artifacts:  
  type: zip
  files:
    - search.yaml